table 'analytics dim_date'
	lineageTag: 5e9ef1d2-9b15-4086-a77d-9e901fe93cad
	dataCategory: Time

	column date_key
		dataType: int64
		formatString: 0
		lineageTag: 5976ca52-07cb-4b78-b8a7-32e24d1f3bf7
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column full_date
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: de3e49a3-176b-4bdc-87b7-f091b0b1c74d
		summarizeBy: none
		sourceColumn: full_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column year
		dataType: int64
		formatString: 0
		lineageTag: d8787a34-9491-4692-b77a-8906817afa2d
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 82f5b3d8-3a39-4aee-b6fa-e91f8a2284b6
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month_number
		dataType: int64
		formatString: 0
		lineageTag: dbca233f-5c1d-4849-83f2-90d6bc03dbe5
		summarizeBy: sum
		sourceColumn: month_number

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 7d8ceeed-c90f-4936-8669-2f572c1c8a71
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: 742d6aa3-f4f6-41d4-b316-7b819280f3c4
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column day_of_month
		dataType: int64
		formatString: 0
		lineageTag: 878f727c-55cc-477c-b85a-32bd9621d575
		summarizeBy: sum
		sourceColumn: day_of_month

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: 16f73b94-20b2-49b6-a512-1554a1b4acfc
		summarizeBy: none
		sourceColumn: day_name

		annotation SummarizationSetBy = Automatic

	column day_of_week
		dataType: int64
		formatString: 0
		lineageTag: 1aa74b76-249b-477b-87c6-adbb305d5dcd
		summarizeBy: sum
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

	column week_of_year
		dataType: int64
		formatString: 0
		lineageTag: c6c0f51d-a03b-4073-a94b-15a1819b7068
		summarizeBy: sum
		sourceColumn: week_of_year

		annotation SummarizationSetBy = Automatic

	partition 'analytics dim_date' = m
		mode: import
		source =
				let
				    Source = PostgreSQL.Database("localhost", "hospital360"),
				    analytics_dim_date = Source{[Schema="analytics",Item="dim_date"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(analytics_dim_date, each ([date_key] <> null and [date_key] <> 0 and [date_key] <> ""))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

