-- Hospital360 Analytics V1 star schema.
-- Creates analytics objects only; it does not modify raw or staging data.
\set ON_ERROR_STOP on

BEGIN;

CREATE TABLE IF NOT EXISTS analytics.dim_date (
    date_key integer PRIMARY KEY,
    full_date date UNIQUE,
    year smallint,
    quarter smallint,
    month_number smallint,
    month_name text,
    year_month text,
    day_of_month smallint,
    day_name text,
    day_of_week smallint,
    week_of_year smallint,
    CONSTRAINT ck_dim_date_key CHECK (
        date_key = 0 OR date_key = to_char(full_date, 'YYYYMMDD')::integer
    )
);

CREATE TABLE IF NOT EXISTS analytics.dim_patient (
    patient_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id text NOT NULL UNIQUE,
    birth_date date,
    death_date date,
    marital_status text,
    race text,
    ethnicity text,
    gender text,
    birthplace text,
    city text,
    state text,
    county text,
    fips text,
    zip text,
    latitude numeric,
    longitude numeric,
    source_system text NOT NULL,
    source_table text NOT NULL,
    source_row_hash text
);

-- Provider attributes are limited to identifiers and observed source roles because
-- the approved six-table staging scope does not include a provider master source.
CREATE TABLE IF NOT EXISTS analytics.dim_provider (
    provider_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id text NOT NULL UNIQUE,
    observed_as_encounter_provider boolean NOT NULL DEFAULT false,
    observed_as_claim_provider boolean NOT NULL DEFAULT false,
    observed_as_claim_supervisor boolean NOT NULL DEFAULT false,
    observed_as_claim_referrer boolean NOT NULL DEFAULT false,
    observed_as_transaction_provider boolean NOT NULL DEFAULT false,
    observed_as_transaction_supervisor boolean NOT NULL DEFAULT false,
    is_inferred_reference boolean NOT NULL DEFAULT true,
    source_system text NOT NULL,
    source_scope text NOT NULL
);

-- Organization attributes are inferred from encounter and place-of-service IDs.
CREATE TABLE IF NOT EXISTS analytics.dim_organization (
    organization_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id text NOT NULL UNIQUE,
    observed_as_encounter_organization boolean NOT NULL DEFAULT false,
    observed_as_place_of_service boolean NOT NULL DEFAULT false,
    is_inferred_reference boolean NOT NULL DEFAULT true,
    source_system text NOT NULL,
    source_scope text NOT NULL
);

-- Payer attributes are inferred from encounter and claim insurance references.
CREATE TABLE IF NOT EXISTS analytics.dim_payer (
    payer_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payer_id text NOT NULL UNIQUE,
    observed_as_encounter_payer boolean NOT NULL DEFAULT false,
    observed_as_primary_claim_payer boolean NOT NULL DEFAULT false,
    observed_as_secondary_claim_payer boolean NOT NULL DEFAULT false,
    is_inferred_reference boolean NOT NULL DEFAULT true,
    source_system text NOT NULL,
    source_scope text NOT NULL
);

CREATE TABLE IF NOT EXISTS analytics.dim_condition (
    condition_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_system text NOT NULL,
    condition_code text NOT NULL,
    condition_description text,
    source_system text NOT NULL,
    source_table text NOT NULL,
    CONSTRAINT uq_dim_condition_business_key UNIQUE (code_system, condition_code)
);

CREATE TABLE IF NOT EXISTS analytics.dim_procedure (
    procedure_key integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_system text NOT NULL,
    procedure_code text NOT NULL,
    procedure_description text,
    source_system text NOT NULL,
    source_table text NOT NULL,
    CONSTRAINT uq_dim_procedure_business_key UNIQUE (code_system, procedure_code)
);

CREATE TABLE IF NOT EXISTS analytics.fact_encounter (
    encounter_fact_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_id text NOT NULL UNIQUE,
    patient_key integer NOT NULL REFERENCES analytics.dim_patient(patient_key),
    provider_key integer NOT NULL REFERENCES analytics.dim_provider(provider_key),
    organization_key integer NOT NULL REFERENCES analytics.dim_organization(organization_key),
    payer_key integer NOT NULL REFERENCES analytics.dim_payer(payer_key),
    start_date_key integer NOT NULL REFERENCES analytics.dim_date(date_key),
    stop_date_key integer NOT NULL REFERENCES analytics.dim_date(date_key),
    start_at timestamptz,
    stop_at timestamptz,
    encounter_class text,
    encounter_code text,
    encounter_description text,
    reason_code text,
    reason_description text,
    base_encounter_cost numeric,
    total_claim_cost numeric,
    payer_coverage numeric,
    source_system text NOT NULL,
    source_table text NOT NULL,
    source_row_hash text
);

CREATE TABLE IF NOT EXISTS analytics.fact_claim (
    claim_fact_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id text NOT NULL UNIQUE,
    encounter_id text,
    patient_key integer NOT NULL REFERENCES analytics.dim_patient(patient_key),
    provider_key integer NOT NULL REFERENCES analytics.dim_provider(provider_key),
    supervising_provider_key integer NOT NULL REFERENCES analytics.dim_provider(provider_key),
    referring_provider_key integer NOT NULL REFERENCES analytics.dim_provider(provider_key),
    organization_key integer NOT NULL REFERENCES analytics.dim_organization(organization_key),
    primary_payer_key integer NOT NULL REFERENCES analytics.dim_payer(payer_key),
    secondary_payer_key integer NOT NULL REFERENCES analytics.dim_payer(payer_key),
    current_illness_date_key integer NOT NULL REFERENCES analytics.dim_date(date_key),
    service_date_key integer NOT NULL REFERENCES analytics.dim_date(date_key),
    last_billed_date_key_1 integer NOT NULL REFERENCES analytics.dim_date(date_key),
    last_billed_date_key_2 integer NOT NULL REFERENCES analytics.dim_date(date_key),
    last_billed_date_key_primary integer NOT NULL REFERENCES analytics.dim_date(date_key),
    current_illness_at timestamptz,
    service_at timestamptz,
    last_billed_at_1 timestamptz,
    last_billed_at_2 timestamptz,
    last_billed_at_primary timestamptz,
    department_id integer,
    patient_department_id integer,
    status_1 text,
    status_2 text,
    status_primary text,
    healthcare_claim_type_id_1 integer,
    healthcare_claim_type_id_2 integer,
    diagnosis_1 text,
    diagnosis_2 text,
    diagnosis_3 text,
    diagnosis_4 text,
    diagnosis_5 text,
    diagnosis_6 text,
    diagnosis_7 text,
    diagnosis_8 text,
    outstanding_1 numeric,
    outstanding_2 numeric,
    outstanding_primary numeric,
    source_system text NOT NULL,
    source_table text NOT NULL,
    source_row_hash text
);

CREATE TABLE IF NOT EXISTS analytics.fact_claim_transaction (
    claim_transaction_fact_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id text NOT NULL UNIQUE,
    claim_id text,
    encounter_id text,
    charge_id text,
    patient_key integer NOT NULL REFERENCES analytics.dim_patient(patient_key),
    provider_key integer NOT NULL REFERENCES analytics.dim_provider(provider_key),
    supervising_provider_key integer NOT NULL REFERENCES analytics.dim_provider(provider_key),
    organization_key integer NOT NULL REFERENCES analytics.dim_organization(organization_key),
    claim_primary_payer_key integer NOT NULL REFERENCES analytics.dim_payer(payer_key),
    from_date_key integer NOT NULL REFERENCES analytics.dim_date(date_key),
    to_date_key integer NOT NULL REFERENCES analytics.dim_date(date_key),
    from_at timestamptz,
    to_at timestamptz,
    transaction_type text,
    method text,
    procedure_code text,
    modifier_1 text,
    modifier_2 text,
    diagnosis_ref_1 integer,
    diagnosis_ref_2 integer,
    diagnosis_ref_3 integer,
    diagnosis_ref_4 integer,
    department_id integer,
    transfer_out_id text,
    transfer_type text,
    patient_insurance_id text,
    fee_schedule_id text,
    units numeric,
    amount numeric,
    unit_amount numeric,
    payments numeric,
    adjustments numeric,
    transfers numeric,
    outstanding numeric,
    source_unset_to_timestamp_warning boolean NOT NULL DEFAULT false,
    source_system text NOT NULL,
    source_table text NOT NULL,
    source_row_hash text
);

CREATE TABLE IF NOT EXISTS analytics.fact_condition_occurrence (
    condition_occurrence_fact_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_id text,
    patient_key integer NOT NULL REFERENCES analytics.dim_patient(patient_key),
    condition_key integer NOT NULL REFERENCES analytics.dim_condition(condition_key),
    encounter_provider_key integer NOT NULL REFERENCES analytics.dim_provider(provider_key),
    encounter_organization_key integer NOT NULL REFERENCES analytics.dim_organization(organization_key),
    encounter_payer_key integer NOT NULL REFERENCES analytics.dim_payer(payer_key),
    start_date_key integer NOT NULL REFERENCES analytics.dim_date(date_key),
    stop_date_key integer NOT NULL REFERENCES analytics.dim_date(date_key),
    start_date date,
    stop_date date,
    source_system text NOT NULL,
    source_table text NOT NULL,
    source_row_hash text
);

CREATE TABLE IF NOT EXISTS analytics.fact_procedure (
    procedure_fact_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encounter_id text,
    patient_key integer NOT NULL REFERENCES analytics.dim_patient(patient_key),
    procedure_key integer NOT NULL REFERENCES analytics.dim_procedure(procedure_key),
    encounter_provider_key integer NOT NULL REFERENCES analytics.dim_provider(provider_key),
    encounter_organization_key integer NOT NULL REFERENCES analytics.dim_organization(organization_key),
    encounter_payer_key integer NOT NULL REFERENCES analytics.dim_payer(payer_key),
    start_date_key integer NOT NULL REFERENCES analytics.dim_date(date_key),
    stop_date_key integer NOT NULL REFERENCES analytics.dim_date(date_key),
    start_at timestamptz,
    stop_at timestamptz,
    reason_code text,
    reason_description text,
    base_cost numeric,
    source_system text NOT NULL,
    source_table text NOT NULL,
    source_row_hash text
);

CREATE INDEX IF NOT EXISTS ix_fact_encounter_patient ON analytics.fact_encounter(patient_key);
CREATE INDEX IF NOT EXISTS ix_fact_encounter_start_date ON analytics.fact_encounter(start_date_key);
CREATE INDEX IF NOT EXISTS ix_fact_claim_patient ON analytics.fact_claim(patient_key);
CREATE INDEX IF NOT EXISTS ix_fact_claim_service_date ON analytics.fact_claim(service_date_key);
CREATE INDEX IF NOT EXISTS ix_fact_claim_encounter_id ON analytics.fact_claim(encounter_id);
CREATE INDEX IF NOT EXISTS ix_fact_claim_transaction_patient ON analytics.fact_claim_transaction(patient_key);
CREATE INDEX IF NOT EXISTS ix_fact_claim_transaction_from_date ON analytics.fact_claim_transaction(from_date_key);
CREATE INDEX IF NOT EXISTS ix_fact_claim_transaction_claim_id ON analytics.fact_claim_transaction(claim_id);
CREATE INDEX IF NOT EXISTS ix_fact_condition_patient ON analytics.fact_condition_occurrence(patient_key);
CREATE INDEX IF NOT EXISTS ix_fact_condition_concept ON analytics.fact_condition_occurrence(condition_key);
CREATE INDEX IF NOT EXISTS ix_fact_procedure_patient ON analytics.fact_procedure(patient_key);
CREATE INDEX IF NOT EXISTS ix_fact_procedure_concept ON analytics.fact_procedure(procedure_key);

COMMENT ON TABLE analytics.fact_encounter IS 'Grain: one row per staged Synthea encounter event.';
COMMENT ON TABLE analytics.fact_claim IS 'Grain: one row per staged Synthea claim header; encounter_id is lineage only, not a fact foreign key.';
COMMENT ON TABLE analytics.fact_claim_transaction IS 'Grain: one row per staged Synthea financial transaction/event line; claim_id and encounter_id are lineage only.';
COMMENT ON TABLE analytics.fact_condition_occurrence IS 'Grain: one row per staged Synthea condition occurrence.';
COMMENT ON TABLE analytics.fact_procedure IS 'Grain: one row per staged Synthea performed procedure occurrence.';

COMMIT;
